apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitlab-scorecard-datasource1
  description: newDescription
  annotations:
    backstage.io/techdocs-ref: dir:.
    harness.io/pipelines: |
      labelA: https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/home/orgs/default/projects/automation/pipelines/quickstart/pipeline-studio/?storeType=INLINE
    harness.io/services: |
      labelA: https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/home/orgs/default/projects/automation/services/nginx?tab=summaryTab
spec:
  type: service
  owner: idpadmin
  lifecycle: experimental
